### ISSUE TITLE
demo site?

### ISSUE THREAD

**Issue by jujes** [hwillson/meteor-recommendation-builder#2]
hi, hava a demo site?
Thanks in advance,

**Comment by hwillson** [comment]
Hi @jujes - no, not yet. This is still very much a work in progress. I should have something ready to show in a couple of weeks. Thanks!

**Comment by jujes** [comment]
@hwillson I have ubuntu 14.04 running into virtualbox to tried but nor success...
can you tell me how deploy?

```
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y git && sudo apt-get install -y g++
curl https://install.meteor.com/ | sh
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
git clone https://github.com/hwillson/meteor-recommendation-builder.git mrb
cd mrb
npm install
npm start
```

**Comment by hwillson** [comment]
@jujes I would recommend holding off for a couple of weeks. Things are under heavy development right now, so there isn't really anything to see. Your deployment steps are correct, it's just the app that isn't ready yet. I'll post back here when there is something to see (and it will work properly). Thanks!

**Comment by jujes** [comment]
@hwillson ok :)
